export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  PROFILE: '/profile',
  ATTENDANCE: '/attendance',
  LEAVE: '/leave',
  LEAVE_APPLY: '/leave/apply',
  TIMESHEETS: '/timesheets',
  TIMESHEETS_LOG: '/timesheets/log',
  TICKETS: '/tickets',
  TICKET_CREATE: '/tickets/create',
  TICKET_DETAIL: '/tickets/:id',
  PAYSLIPS: '/payslips',
  PAYSLIP_DETAIL: '/payslips/:id',
  DOCUMENTS: '/documents',
  DIRECTORY: '/directory',
  HOLIDAYS: '/holidays',
  ANNOUNCEMENTS: '/announcements',
  SETTINGS: '/settings',
  ADMIN_USERS: '/admin/users',
  ADMIN_DEPARTMENTS: '/admin/departments',
  ADMIN_REPORTS: '/admin/reports',
} as const;
